#define __JSON_FOREACH_ITER_2(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_1(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_3(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_2(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_4(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_3(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_5(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_4(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_6(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_5(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_7(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_6(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_8(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_7(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_9(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_8(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_10(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_9(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_11(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_10(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_12(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_11(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_13(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_12(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_14(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_13(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_15(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_14(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_16(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_15(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_17(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_16(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_18(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_17(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_19(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_18(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_20(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_19(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_21(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_20(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_22(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_21(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_23(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_22(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_24(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_23(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_25(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_24(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_26(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_25(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_27(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_26(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_28(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_27(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_29(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_28(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_30(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_29(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_31(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_30(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_32(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_31(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_33(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_32(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_34(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_33(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_35(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_34(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_36(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_35(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_37(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_36(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_38(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_37(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_39(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_38(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_40(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_39(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_41(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_40(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_42(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_41(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_43(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_42(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_44(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_43(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_45(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_44(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_46(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_45(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_47(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_46(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_48(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_47(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_49(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_48(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_50(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_49(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_51(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_50(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_52(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_51(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_53(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_52(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_54(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_53(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_55(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_54(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_56(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_55(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_57(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_56(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_58(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_57(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_59(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_58(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_60(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_59(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_61(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_60(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_62(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_61(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_63(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_62(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_64(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_63(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_65(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_64(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_66(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_65(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_67(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_66(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_68(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_67(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_69(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_68(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_70(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_69(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_71(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_70(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_72(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_71(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_73(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_72(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_74(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_73(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_75(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_74(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_76(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_75(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_77(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_76(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_78(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_77(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_79(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_78(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_80(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_79(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_81(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_80(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_82(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_81(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_83(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_82(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_84(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_83(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_85(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_84(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_86(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_85(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_87(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_86(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_88(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_87(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_89(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_88(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_90(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_89(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_91(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_90(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_92(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_91(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_93(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_92(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_94(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_93(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_95(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_94(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_96(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_95(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_97(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_96(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_98(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_97(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_99(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_98(ACTION, ARG, __VA_ARGS__)

#define __JSON_FOREACH_ITER_100(ACTION, ARG, X, ...) \
	ACTION(ARG, X) \
	__JSON_FOREACH_ITER_99(ACTION, ARG, __VA_ARGS__)

