#define __JSON_FOREACH_ITER_2(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_1(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_3(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_2(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_4(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_3(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_5(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_4(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_6(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_5(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_7(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_6(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_8(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_7(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_9(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_8(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_10(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_9(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_11(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_10(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_12(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_11(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_13(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_12(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_14(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_13(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_15(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_14(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_16(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_15(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_17(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_16(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_18(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_17(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_19(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_18(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_20(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_19(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_21(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_20(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_22(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_21(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_23(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_22(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_24(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_23(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_25(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_24(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_26(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_25(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_27(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_26(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_28(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_27(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_29(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_28(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_30(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_29(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_31(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_30(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_32(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_31(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_33(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_32(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_34(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_33(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_35(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_34(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_36(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_35(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_37(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_36(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_38(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_37(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_39(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_38(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_40(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_39(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_41(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_40(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_42(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_41(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_43(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_42(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_44(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_43(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_45(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_44(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_46(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_45(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_47(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_46(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_48(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_47(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_49(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_48(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_50(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_49(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_51(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_50(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_52(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_51(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_53(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_52(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_54(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_53(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_55(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_54(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_56(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_55(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_57(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_56(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_58(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_57(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_59(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_58(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_60(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_59(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_61(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_60(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_62(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_61(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_63(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_62(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_64(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_63(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_65(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_64(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_66(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_65(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_67(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_66(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_68(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_67(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_69(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_68(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_70(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_69(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_71(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_70(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_72(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_71(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_73(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_72(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_74(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_73(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_75(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_74(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_76(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_75(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_77(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_76(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_78(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_77(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_79(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_78(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_80(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_79(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_81(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_80(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_82(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_81(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_83(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_82(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_84(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_83(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_85(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_84(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_86(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_85(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_87(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_86(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_88(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_87(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_89(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_88(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_90(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_89(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_91(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_90(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_92(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_91(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_93(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_92(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_94(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_93(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_95(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_94(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_96(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_95(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_97(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_96(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_98(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_97(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_99(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_98(ACTION, __VA_ARGS__)

#define __JSON_FOREACH_ITER_100(ACTION, X, ...) \
	ACTION(X) \
	__JSON_FOREACH_ITER_99(ACTION, __VA_ARGS__)

