#include "json.h"

JSON_DEFINE_OBJECT(Name,
	JSON_STRING(Test),
	JSON_STRING(Test),
	JSON_STRING(Test),
	JSON_STRING(Test),
	JSON_STRING(Test),
	JSON_STRING(Test),
	JSON_STRING(Test),
	JSON_STRING(Test),
	JSON_STRING(Test),
	JSON_STRING(Test),
	JSON_STRING(Test)
)
