#include "json.h"

JSON_DEFINE_OBJECT(object_name,
	JSON_STRING(field_0),
	JSON_STRING(field_1),
	JSON_STRING(field_2),
	JSON_STRING(field_3),
	JSON_STRING(field_4),
	JSON_STRING(field_5),
	JSON_STRING(field_6),
	JSON_STRING(field_7),
	JSON_STRING(field_8),
	JSON_STRING(field_9),
	JSON_STRING(field_10),
	JSON_STRING(field_11),
	JSON_STRING(field_12),
	JSON_STRING(field_13),
	JSON_STRING(field_14),
	JSON_STRING(field_15),
	JSON_STRING(field_16),
	JSON_STRING(field_17),
	JSON_STRING(field_18),
	JSON_STRING(field_19),
	JSON_STRING(field_20)
)
